---
title: "Rough Twin Location Distance Analyses"
output: html_notebook
date: 2017-03-01
---
A hacky initial approach to looking at twin GPS distances by twin status.

```{r setup}
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(geosphere)

twin_info <- read_rds('../data/raw/Robin_paper-entry_12-6-16.rds')
locations <- read_rds('../data/raw/Michigan_DB_user_location_02_01_17.rds')
id_mapping <- read_csv('../data/processed/id_mapping.csv', col_types = 
                         cols(
                           T1 = col_character(),
                           T2 = col_character(),
                           T1_alternate_id = col_character(),
                           T2_alternate_id = col_character(),
                           bestzygos = col_character()
                         ))
```

```{r}
locations <- locations %>%
  select(creation_date:sample_timezone) %>%
  na.omit() %>%
  unique() %>%
  mutate(creation_date = ymd_hms(creation_date), sample_time = ymd_hms(sample_time))
```

```{r}
locations %>% filter(sample_time > ymd('2015-01-01'), sample_time < ymd('2017-02-02')) %>% ggplot(aes(x = sample_time)) + geom_histogram()
```

```{r}
locations <- locations %>% filter(accuracy < 500, sample_time > ymd('2015-01-01'), sample_time < ymd('2017-02-02'))
```


```{r}
id_mapping <- bind_rows(tibble(SVID = id_mapping$T1, Colorado_ID = id_mapping$T1_alternate_id), tibble(SVID = id_mapping$T2, Colorado_ID = id_mapping$T2_alternate_id))

twin_info <- left_join(twin_info, id_mapping, by = c('ID1' = 'SVID'))
```

```{r}
# Get the average location points per day for each twin
density <- rep(NA, nrow(twin_info))
for (twin in seq(to = nrow(twin_info))) {
  twin_locs <- filter(locations, user_id == twin_info$Colorado_ID[twin])
  if (nrow(twin_locs) == 0) {next()}
  density[twin] <- nrow(twin_locs) / as.numeric(max(twin_locs$sample_time) - min(twin_locs$sample_time))
}

density %>% tibble() %>% ggplot(aes(x = density)) + geom_density()
```


```{r}
# Standardize locations for each twin pair to a ten minute grid
std_locs <- tibble(DateTime = as.POSIXct(character()),
                  Colorado_ID = character(),
                  latitude = numeric(),
                  longitude = numeric())

for (twin_pair in seq(to = nrow(twin_info), by = 2)) {
  pair_locs <- filter(locations, user_id %in% twin_info$Colorado_ID[twin_pair:(twin_pair + 1)])
  if (nrow(pair_locs) == 0) {
    next()
  }
  time_grid <- seq(min(pair_locs$sample_time), max(pair_locs$sample_time), 60*10)
  results <- expand.grid(DateTime = time_grid, Colorado_ID = twin_info$Colorado_ID[twin_pair:(twin_pair + 1)], stringsAsFactors = F)
  results[, c('latitude', 'longitude')] <- NA
  
  for (row in seq(to = nrow(results))) {
    subset <- filter(pair_locs, user_id == results[row, 2], sample_time < results[row, 1] + minutes(5), sample_time > results[row, 1] - minutes(5))
    if (nrow(subset) == 0) {
      next()
    }
    else {
      results[row, 3] <- mean(subset$latitude, na.rm = T)
      results[row, 4] <- mean(subset$longitude, na.rm = T)
    }
  }
  std_locs <- bind_rows(std_locs, results)
}
```


```{r}
# Get the mean distance for each twin pair
tp_dists <- tibble(tp_id = character(),
                   zygosity = character(),
                   mean_dist = numeric())

std_locs <- std_locs[complete.cases(std_locs), ]
for (twin_pair in seq(to = nrow(twin_info), by = 2)) {
  t1_locs <- filter(std_locs, Colorado_ID == twin_info$Colorado_ID[twin_pair])
  t2_locs <- filter(std_locs, Colorado_ID == twin_info$Colorado_ID[(twin_pair + 1)])
  t1_locs <- filter(t1_locs, DateTime %in% t2_locs$DateTime)
  t2_locs <- filter(t2_locs, DateTime %in% t1_locs$DateTime)
  if (nrow(t1_locs) == 0) {next()}
  t_dist <- distCosine(t1_locs[, c('longitude', 'latitude')], t2_locs[, c('longitude', 'latitude')])
  tp_dists[nrow(tp_dists) + 1, ] <- list(twin_info$Colorado_ID[twin_pair], twin_info$bestzygos[twin_pair], mean(t_dist))
}
```

```{r}
ggplot(tp_dists, aes(x = mean_dist, fill = zygosity)) + geom_density(alpha = 0.5)
```

