# Take the individual parameters generated by dpw_quadratic_model.R
# and use OpenMx to fit univariate ACE models

library(readr)
library(dplyr)

source("src/models/utils.R")

params <- read_rds("data/models/dpw_quadratic_parameters.rds")
id_mapping <- read_csv("data/processed/id_mapping.csv", col_types = "ccccc")

# Get the parameters for each twin pair
id_mapping <- select(id_mapping, T1_id = T1_alternate_id, T2_id = T2_alternate_id, bestzygos)

id_mapping <- left_join(id_mapping, params, by = c("T1_id" = "user_id"))
id_mapping <- select(id_mapping, T1_id:bestzygos, intercept1 = intercept, slope1 = slope, quadratic1 = quadratic)

id_mapping <- left_join(id_mapping, params, by = c("T2_id" = "user_id"))
id_mapping <- select(id_mapping, T1_id:quadratic1, intercept2 = intercept, slope2 = slope, quadratic2 = quadratic)

# Separate out MZs and DZs
mz_data <- filter(id_mapping, bestzygos == "MZ")
dz_data <- filter(id_mapping, bestzygos %in% c("DZ", "OS"))

# Select just the phenotypes
mz_data <- mz_data[, 4:9]
dz_data <- dz_data[, 4:9]

# Rescale to variances around 1
mz_data_scale <-
  mutate_all(mz_data, funs(. * round(sqrt(
    1 / var(., use = "complete.obs")
  ), 1)))

dz_data_scale <-
  mutate_all(dz_data, funs(. * round(sqrt(
    1 / var(., use = "complete.obs")
  ), 1)))

# Fit the univariate models of the parameters and extract the a2, c2, and e2 estimates
print("Summary of the univariate model of intercept for drinks per week:")

intercept_fit <-
  fit_ace_univariate(mz_data,
                     dz_data,
                     "intercept1",
                     "intercept2"
  )
summary(intercept_fit)
intercept_fit_comps <-
  tibble(
    lbound = intercept_fit$output$confidenceIntervals[, 1],
    estimate = intercept_fit$output$confidenceIntervals[, 2],
    ubound = intercept_fit$output$confidenceIntervals[, 3],
    component = c("a2", "c2", "e2"),
    pheno = rep("intercept", 3)
  )

print("Summary of the univariate model of slope for drinks per week:")

slope_fit <-
  fit_ace_univariate(mz_data,
                     dz_data,
                     "slope1",
                     "slope2"
  )
summary(slope_fit)
slope_fit_comps <-
  tibble(
    lbound = slope_fit$output$confidenceIntervals[, 1],
    estimate = slope_fit$output$confidenceIntervals[, 2],
    ubound = slope_fit$output$confidenceIntervals[, 3],
    component = c("a2", "c2", "e2"),
    pheno = rep("slope", 3)
  )

print("Summary of the univariate model of the quadratic term for drinks per week:")

quadratic_fit <-
  fit_ace_univariate(mz_data,
                     dz_data,
                     "quadratic1",
                     "quadratic2"
  )
summary(quadratic_fit)
quadratic_fit_comps <-
  tibble(
    lbound = quadratic_fit$output$confidenceIntervals[, 1],
    estimate = quadratic_fit$output$confidenceIntervals[, 2],
    ubound = quadratic_fit$output$confidenceIntervals[, 3],
    component = c("a2", "c2", "e2"),
    pheno = rep("quadratic", 3)
  )

# Combine and write out the variance component estimates
all_comps <- bind_rows(intercept_fit_comps, slope_fit_comps, quadratic_fit_comps)
all_comps$pheno <- factor(all_comps$pheno, levels = c("intercept", "slope", "quadratic"))
write_rds(all_comps, "data/models/dpw_quadratic_ACE_comps.rds")
