# Take the random slopes and intercepts generated by mar_per_week_linear_model.R
# and use OpenMx to fit a bivariate ACE model

library(readr)
library(dplyr)

source("src/models/utils.R")

re_est <- read_rds("data/models/mar_per_week_linear_random_effects.rds")
id_mapping <- read_csv("data/processed/id_mapping.csv", col_types = "ccccc")

# Filter out the intercept and slope terms
intercepts <- filter(re_est, term == "d_1i")
slopes <- filter(re_est, term == "d_2i")

# Get the slope and intercepts for each twin pair
id_mapping <- select(id_mapping, T1_id = T1_alternate_id, T2_id = T2_alternate_id, bestzygos)

id_mapping <- left_join(id_mapping, intercepts, by = c("T1_id" = "twin"))
id_mapping <- select(id_mapping, T1_id:bestzygos, intercept1 = estimate)

id_mapping <- left_join(id_mapping, intercepts, by = c("T2_id" = "twin"))
id_mapping <- select(id_mapping, T1_id:intercept1, intercept2 = estimate)

id_mapping <- left_join(id_mapping, slopes, by = c("T1_id" = "twin"))
id_mapping <- select(id_mapping, T1_id:intercept2, slope1 = estimate)

id_mapping <- left_join(id_mapping, slopes, by = c("T2_id" = "twin"))
id_mapping <- select(id_mapping, T1_id:slope1, slope2 = estimate)

# Separate out MZs and DZs
mz_data <- filter(id_mapping, bestzygos == "MZ")
dz_data <- filter(id_mapping, bestzygos %in% c("DZ", "OS"))

# Select just the phenotypes
mz_data <- mz_data[, 4:7]
dz_data <- dz_data[, 4:7]

# Fit the bivariate model of slope and intercept
print("Summary of the bivariate model of slope and intercept for marijuana uses per week:")

both_fit <-
  fit_ace_bivariate(mz_data,
                    dz_data,
                    "intercept1",
                    "intercept2",
                    "slope1",
                    "slope2"
  )
summary(both_fit)
