# Take the individual slopes and intercepts generated by mar_per_week_linear_model.R
# and use OpenMx to fit a bivariate ACE model

library(readr)
library(dplyr)

source("src/models/utils.R")

params <- read_rds("data/models/mpw_linear_parameters.rds")
id_mapping <- read_csv("data/processed/id_mapping.csv", col_types = "ccccc")

# Get the slope and intercepts for each twin pair
id_mapping <- select(id_mapping, T1_id = T1_alternate_id, T2_id = T2_alternate_id, bestzygos)

id_mapping <- left_join(id_mapping, params, by = c("T1_id" = "user_id"))
id_mapping <- select(id_mapping, T1_id:bestzygos, intercept1 = intercept, slope1 = slope)

id_mapping <- left_join(id_mapping, params, by = c("T2_id" = "user_id"))
id_mapping <- select(id_mapping, T1_id:slope1, intercept2 = intercept, slope2 = slope)

# Separate out MZs and DZs
mz_data <- filter(id_mapping, bestzygos == "MZ")
dz_data <- filter(id_mapping, bestzygos %in% c("DZ", "OS"))

# Select just the phenotypes
mz_data <- mz_data[, 4:7]
dz_data <- dz_data[, 4:7]

# Fit the bivariate model of slope and intercept
print("Summary of the bivariate model of slope and intercept for marijuana uses per week:")

both_fit <-
  fit_ace_bivariate(mz_data,
                    dz_data,
                    "intercept1",
                    "intercept2",
                    "slope1",
                    "slope2"
  )
summary(both_fit)

# Write out the variance component estimates
var_comps <- tibble(
  lbound = both_fit$output$confidenceIntervals[, 1],
  estimate = both_fit$output$confidenceIntervals[, 2],
  ubound = both_fit$output$confidenceIntervals[, 3],
  component = c("a2", "c2", "e2", "a2", "c2", "e2"),
  pheno = c(rep("intercept", 3), rep("slope", 3))
)
write_rds(var_comps, "data/models/mpw_linear_ACE_comps.rds")
