# Take the individual parameters generated by at_home_quadratic_model.R
# and use OpenMx to fit univariate ACE models

library(readr)
library(dplyr)

source("src/models/utils.R")

params <- read_rds("data/models/par_mon_quadratic_parameters.rds")
id_mapping <- read_csv("data/processed/id_mapping.csv", col_types = "ccccc")

# Center the intercept and slope estimates at zero
params <- mutate(params, intercept = intercept - 17)

# Get the parameters for each twin pair
id_mapping <- select(id_mapping, T1_id = T1_alternate_id, T2_id = T2_alternate_id, bestzygos)

id_mapping <- left_join(id_mapping, params, by = c("T1_id" = "user_id"))
id_mapping <- select(id_mapping, T1_id:bestzygos, intercept1 = intercept, slope1 = slope, quadratic1 = quadratic)

id_mapping <- left_join(id_mapping, params, by = c("T2_id" = "user_id"))
id_mapping <- select(id_mapping, T1_id:quadratic1, intercept2 = intercept, slope2 = slope, quadratic2 = quadratic)

# Separate out MZs and DZs
mz_data <- filter(id_mapping, bestzygos == "MZ")
dz_data <- filter(id_mapping, bestzygos %in% c("DZ", "OS"))

# Select just the phenotypes
mz_data <- mz_data[, 4:9]
dz_data <- dz_data[, 4:9]

# Scale the phenotypes to have approximately equal variances
mz_data <-
  mutate_all(mz_data, funs(. * round(sqrt(
    1 / var(., use = "complete.obs")
  ), 1)))

dz_data <-
  mutate_all(dz_data, funs(. * round(sqrt(
    1 / var(., use = "complete.obs")
  ), 1)))

# Fit the trivariate model of the parameters and extract the a2, c2, and e2 estimates

tri_fit <-
  fit_ace_trivariate(mz_data,
                     dz_data,
                     "intercept1",
                     "intercept2",
                     "slope1",
                     "slope2",
                     "quadratic1",
                     "quadratic2"
  )
summary(tri_fit)

var_comps <- extract_trivariate_comps(tri_fit)
write_rds(var_comps, "data/models/par_mon_quadratic_ACE_comps.rds")
